[package]
name = "chimer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
daemonize-me = "2.0"
notify-rust = "4"
chrono = "0.4"
rodio = "0.15.0"
